= Introduction

== Limitations of single reference genomes

A single reference genome cannot faithfully represent the genetic variation within a species. Sequences present in some individuals but absent from the reference are invisible to any reference-anchored analysis, and regions that differ substantially from the reference are poorly characterized regardless of the analytical method used @garrison2018. This representation gap introduces systematic reference bias: variant callers underperform in divergent regions, structural variants are missed or mischaracterized, and novel sequences carried by non-reference individuals can be lost @paten2017. These limitations have become increasingly apparent as whole-genome sequencing costs have decreased and researchers have begun characterizing genetic diversity across broader populations.

== Pangenome graphs as a solution

A pangenome is defined as the complete set of genomic elements within a species or clade @eizenga2020. Moving from a single-reference framework to a pangenomic one means incorporating genetic variation from multiple individuals into a unified representation, rather than treating one genome as the standard against which all others are compared.

In a variation graph (also called a pangenome graph), DNA sequences are stored as nodes and the adjacency relationships between them as edges; technically, the graph is a bidirected sequence graph in which each node carries a DNA string and each edge connects a side (5' or 3') of one node to a side of another. A haplotype corresponds to a walk through this graph, and variant sites appear as bubbles---pairs of paths that diverge from and reconverge at shared anchor nodes. Each input genome is encoded as a walk traversing the graph @secomandi2025. Graphs are stored and exchanged in GFA (Graphical Fragment Assembly) format. This approach captures the full spectrum of population diversity, from single-nucleotide polymorphisms (SNPs) to large structural variants (SVs), and provides a data structure capable of simultaneously representing and analyzing hundreds of genomes at gigabase scale---a challenge that traditional reference-based methods cannot address @liao2023. Pangenome graphs have proven successful in representing human genetic variation through the Human Pangenome Reference Consortium (HPRC) and in addressing evolutionary questions across diverse taxa @liao2023 @secomandi2025 @wang2022.

== PGGB: Reference-free pangenome construction

Several methods exist for constructing pangenome graphs, but most are biased because they rely on reference-guided or phylogenetic-tree-guided approaches @garrison2024. In these methods, the choice of reference or guide tree constrains the graph topology: variation is anchored to one genome's coordinate system, and structural differences not captured by that backbone can be missed or distorted. The PanGenome Graph Builder (PGGB) overcomes these limitations through a reference-free pipeline to construct unbiased pangenome graphs @garrison2024. PGGB uses all-to-all whole-genome alignments, comparing every input sequence to every other input sequence without privileging any genome as a reference. All genomes are treated equivalently, without input order or phylogenetic dependencies, and each genome can serve as a potential reference for downstream analysis.

The PGGB pipeline integrates four core modules:

+ *WFMASH: All-to-all whole-genome alignment.* WFMASH performs all-to-all pairwise alignment of the input sequences @guarracino2021wfmash. It uses an extension of MashMap for rapid homology detection, finding segment-level similarities at a specified average nucleotide identity, and then computes base-level alignments using WFlign, which applies the bidirectional Wavefront Algorithm (BiWFA) for gap-affine alignment of each segment. By aligning every sequence directly against every other, WFMASH avoids reference or order bias: each sequence in the pangenome can serve as a potential reference.

+ *SEQWISH: Graph induction from alignments.* SEQWISH converts the set of input genomes together with their pairwise alignments into a variation graph @garrison2023. In this graph, each input genome is fully embedded and can be extracted as a labeled path. SEQWISH also recovers transitive homology relationships---that is, if sequence A aligns to B and B aligns to C, the graph will reflect the relationship between A and C even if they were not directly aligned. SEQWISH scales to terabase-pair datasets through disk-backed processing.

+ *SMOOTHXG: Graph normalization.* The raw variation graph produced by SEQWISH contains spurious local complexity. SMOOTHXG resolves this by dividing the graph into blocks and realigning each block with Partial Order Alignment (POA), iterating to reduce edge effects. Multiple smoothing passes with different block-length targets can be chained for progressive refinement.

+ *GFAFFIX: Redundancy removal.* After smoothing, GFAFFIX identifies and collapses walk-preserving redundant node boundaries---adjacent nodes whose overlapping prefixes and suffixes are identical and can be merged without altering any path through the graph---to produce a streamlined final graph. The output graph is then sorted using ODGI @guarracino2022odgi.

PGGB has been tested in the HPRC, where it contributed to the first draft human pangenome reference @liao2023, and has been widely adopted for applications from microbial genomics @shoer2024 to crop improvement @schreiber2024, evolutionary genomics @bolognini2024, and mammalian reference genome projects @villani2025 @villani2025thesis. The complete workflow described in this protocol is illustrated in Fig. 1.

An alternative approach to pangenome graph construction is Minigraph-Cactus (MC) @hickey2024, which uses a reference-guided strategy with minigraph for SV-scale backbone construction followed by Cactus for base-level alignment. PGGB is preferred when reference bias must be strictly avoided, when the evolutionary relationships among input genomes are unknown or complex, or when complete resolution of all variation (including within repetitive regions) is desired. MC scales approximately linearly with the number of input genomes due to its reference-guided progressive strategy, whereas PGGB's all-to-all alignment scales quadratically, making MC substantially more efficient for large cohorts (hundreds to thousands of haplotypes). Both PGGB and MC graphs can be used with the vg Giraffe short-read mapper @siren2021 via the `vg autoindex` workflow. The choice between the two depends on the biological question and the characteristics of the dataset (_see_ *Note 4*).

== HXB/BXH rat genetic reference population

The laboratory rat (_Rattus norvegicus_) is a widely used model organism for biomedical research. Wild _R. norvegicus_ populations already harbor relatively limited genetic diversity compared with many other rodent species, and laboratory rat strains descend from a small number of wild-caught founders, creating an initial domestication bottleneck. Subsequent inbreeding to establish defined strains has further reduced diversity within each lineage @dejong2024. Importantly, this two-stage bottleneck---first in the wild, then in the laboratory---means that a pangenome built from a modest number of inbred strains can capture a large fraction of the total genetic variation segregating among commonly used laboratory rats, making the pangenome approach particularly efficient in this species.

Genetic reference populations such as the HXB/BXH recombinant inbred (RI) strains serve as powerful tools for investigating genotype--phenotype relationships @pravenec1989. The HXB/BXH panel originated from crossing the Spontaneously Hypertensive Rat (SHR/OlaIpcv) and Brown Norway (BN-Lx/Cub) strains, creating 31 independent RI strains that segregate for alleles affecting blood pressure, metabolic traits and behavioral phenotypes relevant to human disease @printz2003. Because each RI strain is inbred, assemblies are effectively haploid, which simplifies pangenome construction: there is no need to phase diploid haplotypes, and each genome maps to a single path through the graph. Moreover, the parental strains of the HXB/BXH panel overlap with the founders of heterogeneous stock (HS) rat populations used for fine-mapping quantitative trait loci (QTLs); a pangenome that includes RI assemblies can therefore serve as a reference for imputation and variant discovery in those outbred cohorts as well.

The panel has been extensively phenotyped over more than three decades, generating a vast dataset of quantitative molecular and physiological phenotypes available through GeneNetwork @mulligan2017. This combination of genetic stability, phenotypic depth, and relevance to human disease makes the HXB/BXH panel an ideal test case for demonstrating the utility of pangenome approaches in a model organism context.

== Challenges and future directions

As pangenome projects scale to hundreds or thousands of genomes, two challenges become prominent. First, explicit graph construction remains computationally intensive: all-to-all alignment scales quadratically with the number of input genomes, building a graph from hundreds of genomes requires days of computation and hundreds of gigabytes of memory, and adding a single new genome necessitates a full rebuild @garrison2024. Second, the resulting graphs are large and complex data structures that resist interactive exploration; current visualization tools such as ODGI can produce static one- and two-dimensional layouts, but dynamic, on-the-fly visualization of pangenome graphs at genome scale remains an open problem.

Implicit pangenome graphs offer a complementary paradigm that addresses the scaling barrier @guarracino2025impg. Rather than collapsing all alignments into an explicit graph, the Implicit Pangenome Graph (IMPG) approach operates directly on pairwise alignments, indexing them with coitrees (cache-oblivious interval trees) and traversing them to discover both direct and transitive homology relationships. Because each alignment file is indexed independently, incorporating a new genome requires only aligning it to a representative subset---an effort that scales linearly rather than quadratically with cohort size. This approach enables population-scale queries on commodity hardware and would allow researchers to extend the HXB/BXH pangenome incrementally as new strains are sequenced (_see_ *Note 14*).

This protocol describes a complete computational workflow applied to the HXB/BXH panel as a companion to @villani2025: reference-free graph construction with PGGB, variant calling and validation, structural variant analysis, and phenome-wide association mapping linking pangenome-derived variants to the panel's extensive phenotype collection. The pre-built HXB/BXH pangenome graph and associated VCF files are available at #link("https://github.com/Flavia95/HXB_rat_pangenome_manuscript")[github.com/Flavia95/HXB\_rat\_pangenome\_manuscript].
