#let fixme(txt) = text(red,"Fixme:" + txt)


= Introduction

== Limitations of single linear reference genomes

Genomic analyses have long relied on a single linear reference genome to serve as the coordinate system for read mapping, variant calling, and functional annotation. However, no single linear reference genome can represent the full spectrum of genetic variation within a species. Sequences present in some individuals but absent from the reference are invisible to any reference-anchored analysis, and regions that differ substantially from the reference are poorly characterized regardless of the analytical method used @garrison2018. This representation gap creates systematic reference bias: variant callers underperform in divergent regions, structural variants (SVs) are missed or mischaracterized, and novel sequences carried by non-reference individuals are lost entirely @paten2017. As long-read sequencing has made it feasible to produce complete, haplotype-resolved assemblies for many individuals, the scale of what a single reference misses has become uncomfortably clear. The Human Pangenome Reference Consortium (HPRC), for example, found hundreds of megabases of sequence absent from the GRCh38 reference, with marked improvements in variant detection across diverse populations @liao2023 @wang2022. Similar gaps have been documented in livestock, crop species, and non-model organisms, confirming that reference bias is a universal limitation rather than one confined to human genomics @schreiber2024 @secomandi2025.

== Pangenome graphs as a solution

A pangenome, the complete set of genomic elements within a species or clade @eizenga2020, addresses this limitation by incorporating multiple genomes into a single unified representation, rather than treating one genome as the standard against which all others are measured. In practice, a widely used way to encode a pangenome is as a variation graph (also called a pangenome graph). In this data structure, DNA sequences are stored as nodes and adjacency relationships as edges; technically, the graph is a bidirected sequence graph in which each node carries a DNA string and each edge connects a side of one node to a side of another @eizenga2020. Each input genome corresponds to a walk (also called a path) through the graph, and variant sites appear as bubbles, that is pairs of paths that diverge from and reconverge at shared anchor nodes @secomandi2025. The structure of a variation graph is illustrated in the bottom-left panel of Fig. 1. Graphs are stored and exchanged in GFA (Graphical Fragment Assembly) format @gfa_spec.

More formally, a pangenome graph is a bidirected graph $G = (N, E, P)$ where each node $n in N$ carries a DNA label $sigma(n)$ and each edge $e in E$ connects a specific side (left or right) of one node to a side of another, reflecting the strandedness of double-stranded DNA. A walk through $G$ is an ordered sequence of node traversals, each specifying the node and its orientation (forward or reverse complement); every input genome is embedded in the graph as a named walk, conventionally called a path. Variant sites are identified through the snarl decomposition @paten2017: a snarl is a subgraph bounded by two nodes (the source and sink) such that every walk entering through the source must exit through the sink, forming a bubble. Nested snarls capture complex allelic variation hierarchically, with top-level snarls corresponding to independent variant sites and child snarls representing sub-variants within a single allele.

Because the graph encodes the full sequence diversity of its input genomes, it captures variation ranging from single-nucleotide polymorphisms (SNPs) to megabase-scale SVs within a single data structure @liao2023. This representation has already proven its value: the HPRC used pangenome graphs to produce the first draft human pangenome reference, substantially reducing reference bias in variant calling across populations @liao2023. Beyond humans, pangenome graphs are now widely adopted across the tree of life, from crop improvement and biodiversity genomics to microbial and mammalian studies, reflecting a broad shift away from single-reference paradigms @secomandi2025 @schreiber2024.

== Tools for pangenome graph construction

Several methods exist for constructing pangenome graphs, but most rely on reference-guided or phylogenetic-tree-guided approaches that constrain graph topology: variation is anchored to one genome's coordinate system, and structural differences not captured by that backbone can be missed or distorted @garrison2024. The PanGenome Graph Builder (PGGB) takes a deliberately different approach, one that is reference-free and treats all input genomes equivalently @garrison2024. PGGB performs all-to-all whole-genome alignments, comparing every input sequence against every other without privileging any genome as a reference. There is no dependence on input order or phylogenetic assumptions, so each genome can serve as a potential reference for downstream analysis.

The pipeline chains four modules together. WFMASH @guarracino2021wfmash performs all-to-all pairwise alignment using MashMap-based @jain2018 homology detection followed by base-level alignment with the bidirectional Wavefront Algorithm (BiWFA) @marcosola2023. SEQWISH @garrison2023 induces a variation graph from these alignments, recovering transitive homology relationships: if the input alignments contain A aligned to B and B aligned to C, this implies that A also aligns to C, and the graph will reflect the A-C relationship even when the direct A-C alignment is missing from the input. SMOOTHXG @garrison2024 normalizes the raw graph by realigning local blocks with Partial Order Alignment (POA) @lee2002 to remove spurious complexity. Finally, GFAFFIX @garrison2024 collapses redundant node boundaries and the graph is sorted using ODGI @guarracino2022odgi. Algorithmic details and parameter guidance are given in Sections 3.2.2-3.2.5.

PGGB contributed to the first draft human pangenome reference @liao2023 and has since been adopted for applications spanning microbial genomics @shoer2024, crop improvement @schreiber2024, evolutionary genomics @bolognini2024, and mammalian pangenome projects @villani2025 @villani2025thesis @helmy2026. Cluster-based implementations such as nf-core/pangenome further improve scalability by distributing alignments across computing nodes @heumos2024. 

PGGB is not the only option for pangenome construction. The `vg construct` tool @garrison2018 builds a graph by augmenting a linear reference with variants from a VCF file, which works well for known small variants but cannot discover novel structural variation or non-reference sequence. De Bruijn graph methods decompose sequences into fixed-length k-mers and assemble them into a graph; while widely used in assemblers, they are less suited to pangenome representation because k-mer decomposition discards long-range haplotype structure and introduces artificial complexity at repeat boundaries @eizenga2020 @garrison2023. The most widely used alternative to PGGB is Minigraph-Cactus (MC) @hickey2024, which takes a reference-guided strategy: minigraph builds an SV-scale backbone from a chosen reference, and Cactus then performs base-level alignment. This progressive strategy scales approximately linearly with the number of input genomes, making MC substantially more efficient for large cohorts (hundreds to thousands of haplotypes). PGGB is preferred when reference bias must be strictly avoided, when evolutionary relationships among input genomes are unknown or complex, or when complete resolution of all variation, including within repetitive regions, is desired. MC graphs are the recommended input for the vg Giraffe short-read mapper @siren2021; PGGB graphs can also be used via the `vg autoindex` workflow after node chopping with ODGI, but their more complex topology (large snarls, deeply nested variants) can make Giraffe index construction infeasible for large or highly variable genomes. For smaller panels such as HXB/BXH (introduced in Section 1.4; 32 haplotypes, per-chromosome construction), the PGGB-to-Giraffe workflow is practical. The choice between the two graph builders depends on the biological question and dataset characteristics (_see_ *Note 4*).

== HXB/BXH rat genetic reference population

The laboratory rat (_Rattus norvegicus_) has long been a cornerstone model organism for cardiovascular, metabolic, and behavioral research, yet its genomic resources have until recently lagged behind those of the mouse. The HXB/BXH panel is one component of the broader Hybrid Rat Diversity Panel (HRDP), a community resource of inbred strains used for systems genetics in the rat; the HRDP is described in detail in a companion chapter (Dwinell et al., this volume). Laboratory rat strains descend from a small number of wild-caught founders, creating an initial domestication bottleneck, and subsequent inbreeding to establish defined strains further reduced diversity within each lineage @dejong2024. The release of the mRatBN7.2 reference assembly corrected numerous misplaced segments and reduced base-level errors approximately ninefold relative to its predecessor. Mapping 120 laboratory rats to this reference catalogued roughly 20 million sequence variants @dejong2024. Yet this improved reference did not capture the full extent of population-level variation: a pangenome built from the HXB/BXH strains identified approximately 200 Mb of sequence absent from mRatBN7.2 @villani2025. The reference has since been upgraded again to GRCr8, built from 40× PacBio HiFi reads scaffolded with Hi-C and optical mapping; every chromosome grew relative to mRatBN7.2, the Y chromosome tripled in assembled length, and more than 1,100 new protein-coding genes were annotated @li2024grcr8. The HXB/BXH pangenome described here was nonetheless built against mRatBN7.2, as GRCr8 was not yet available at the time of construction. Because laboratory rat strains share a narrow founder base and have been maintained by strict inbreeding, a modest panel of well-chosen strains captures a large fraction of the variation segregating among commonly used laboratory rats. This makes pangenome construction particularly tractable in this species: a few dozen high-quality assemblies, rather than the hundreds needed in more diverse populations, are enough to produce a useful reference.

Genetic reference populations such as the HXB/BXH recombinant inbred (RI) strains provide a powerful framework for investigating genotype-phenotype relationships @pravenec1989. The HXB/BXH panel originated from a cross between the Spontaneously Hypertensive Rat (SHR/OlaIpcv) and Brown Norway-Lx (carrying the polydactyly-luxate syndrome, BN-Lx/Cub) strains, producing 31 independent RI lines that segregate for alleles affecting blood pressure, metabolic traits, and behavioral phenotypes relevant to human disease @printz2003 (Fig. 1). Because each RI strain is fully inbred (_see_ *Note 2*), assemblies are effectively haploid, which simplifies pangenome construction: there is no need to phase diploid haplotypes, and each genome maps to a single path through the graph.

The HXB panel has been extensively phenotyped over more than three decades, generating a deep dataset of molecular and physiological phenotypes available through GeneNetwork @mulligan2017. Recent studies have leveraged this combination of genetic stability and phenotypic depth to map protein quantitative trait loci (pQTLs) in the brain @li2025 and to link pangenome-derived variants with glucose/insulin levels and hippocampal gene expression @villani2025. All of this makes the HXB/BXH panel an ideal test case for demonstrating how pangenome approaches can enhance genotype-phenotype discovery in a model organism.

== Challenges and future directions

As pangenome projects grow to include hundreds or thousands of genomes, the costs grow with them. All-to-all alignment scales quadratically with the number of input genomes, so building a graph from hundreds of genomes can require days of computation and hundreds of gigabytes of memory, and adding a single new genome necessitates a full rebuild @garrison2024. Cluster-level parallelization @heumos2024 mitigates wall-clock time but does not change the underlying algorithmic cost. And once the graph is built, it is itself the next problem: too large and complex for interactive exploration. Tools such as ODGI can produce static one- and two-dimensional layouts @guarracino2022odgi, but dynamic, on-the-fly visualization of pangenome graphs at genome scale remains an open problem.

Implicit pangenome graphs offer a complementary paradigm that addresses the scaling barrier. Rather than collapsing all alignments into an explicit graph, the Implicit Pangenome Graph (IMPG) approach @guarracino2025impg operates directly on pairwise alignments, indexing them with coitrees (cache-oblivious interval trees) and traversing them to discover both direct and transitive homology relationships. Because each alignment file is indexed independently, incorporating a new genome requires only aligning it to a representative subset, an effort that scales linearly rather than quadratically with cohort size. This enables population-scale queries on commodity hardware and would allow researchers to extend the rat pangenome beyond HXB/BXH to additional inbred strains, for example other HRDP members, as they become assembled (_see_ *Note 14*). The convergence of improving assembly quality, scalable graph construction, and deepening phenotype resources positions model organism pangenomics for rapid growth in the coming years (_see_ *Note 16*).

== Scope of this protocol

This protocol describes a complete computational workflow applied to the HXB/BXH panel as a companion to @villani2025: reference-free graph construction with PGGB, variant calling and validation, structural variant analysis, and phenome-wide association mapping linking pangenome-derived variants to the panel's extensive phenotype collection. The complete workflow described in this protocol is illustrated in Fig. 1.
