= Notes

+ *Linked-Read technology considerations.* 10x Genomics Chromium Linked-Reads are not ideal for de novo assembly compared to long-read technologies (PacBio HiFi, Oxford Nanopore). Note that 10x Genomics has discontinued the Chromium Linked-Read product; however, the HXB/BXH assemblies used in this protocol were generated before discontinuation, and the analytical workflow applies equally to assemblies from any sequencing technology. Linked-Read assemblies tend to have more unresolved regions (stretches of Ns) than long-read assemblies, which leads to an overestimation of non-reference sequence when Ns are included in the counting. In the HXB/BXH pangenome, the non-reference content rose from 0.18 Gb (excluding Ns) to 3.9 Gb (including Ns). Despite this limitation, the pangenome still captured substantial genuine novel variation. As long-read sequencing costs continue to decrease, reassembling these strains with PacBio HiFi or Oxford Nanopore would yield more contiguous assemblies and more complete pangenomes.

+ *Handling heterozygous strains.* Among the 31 HXB/BXH strains, BXH2 showed 7.7% heterozygous variants, likely due to a recent breeding error @dejong2024. In principle, such a strain can still be included in the pangenome as a haploid assembly if the assembler selected one haplotype consistently. However, results for this strain should be interpreted with caution, as the assembly may switch between haplotypes in some regions.

+ *Reference genome inclusion rationale.* Although PGGB is reference-free, including the standard reference genome (mRatBN7.2) in the graph is essential for practical reasons: it provides a coordinate system for variant calling (via the `-V` flag), enables comparison with existing reference-based datasets, and allows annotation with established gene models. The reference is treated as just another genome in the graph and does not receive any special treatment during construction.

+ *Choosing between PGGB and Minigraph-Cactus.* Both tools can produce high-quality pangenome graphs, and both are compatible with vg Giraffe @siren2021 for short-read mapping via the `vg autoindex` workflow. The choice depends on the biological question and dataset characteristics. Prefer PGGB when: (i) you need a strictly reference-free graph (e.g., no single genome is a natural reference, or you want to avoid any reference bias); (ii) the input set is moderate in size (tens to low hundreds of haplotypes); (iii) full base-level resolution of all variation, including within repetitive regions, is important. Prefer Minigraph-Cactus when: (i) a reliable reference genome exists and a reference-anchored graph is acceptable; (ii) the input set is very large (hundreds to thousands of haplotypes) and computational efficiency is a priority; (iii) the dataset is too large for all-to-all alignment and a reference-guided strategy is more practical. For the HXB/BXH panel (32 haplotypes, closely related inbred strains), PGGB was the natural choice because reference-free construction avoids privileging either parental genome.

+ *Percent identity parameter selection.* The `-p` parameter sets the minimum percent identity for WFMASH mappings. For closely related inbred strains derived from the same species (such as HXB/BXH rats or BXD mice), values of 95--98% are appropriate. For interspecies comparisons or highly divergent populations, lower values (85--90%) may be needed. Setting this value too low will increase runtime and may introduce spurious alignments; setting it too high will miss genuinely divergent regions.

+ *Segment length parameter.* The `-s` parameter controls the minimum length of mapping segments. Shorter values increase sensitivity but also increase runtime and may capture more spurious short alignments. For closely related mammalian genomes, values between 1,000 and 10,000 bp typically work well.

+ *Sparsification and k-mer filtering for large genome numbers.* All-to-all alignment scales quadratically with the number of input genomes. Two PGGB parameters help manage this. The `-F` parameter sets a k-mer frequency filter threshold: setting `-F 0.001` ignores the top 0.1% most frequent k-mers in minmer sketches, reducing spurious alignments in repetitive regions. For scaling the number of pairwise comparisons themselves, the `-x` parameter activates Erdős--Rényi random sparsification, which randomly subsamples the set of pairwise comparisons. Because SEQWISH recovers transitive homology relationships (if A aligns to B and B to C, then A--C is inferred), the loss of direct alignments is mitigated. With sparsification, a 10× increase in input genomes requires approximately 20× runtime increase rather than 100×. For 32 genomes, the benefit is moderate; for hundreds of genomes, it becomes essential.

+ *Chromosome-by-chromosome construction and troubleshooting.* For mammalian-scale genomes, constructing the pangenome one chromosome at a time is practical and recommended. This approach reduces peak memory requirements, enables parallel execution across cluster nodes, and simplifies debugging. The resulting per-chromosome GFA and VCF files can be concatenated for genome-wide analyses. PGGB can resume interrupted runs: add the `-r` (`--resume`) flag when restarting with the same output directory, and PGGB will skip stages whose outputs already exist. Common failures include: out-of-memory during SMOOTHXG (reduce `-G` block sizes), excessively slow WFMASH alignment (use `-x` sparsification), and fragmented graphs with poor path coverage (verify that `-p` is not set too high for the dataset's divergence).

+ *Variant calling precision in repetitive regions.* Genome-wide accuracy of pangenome-derived variants compared to joint calling was approximately 90%. Exceptions included chromosomes Y and 16, where assembly complexity (chromosome Y) and an abundance of complex variants (chromosome 16) reduced concordance. Within repetitive regions, Sanger validation showed that approximately 90% of unconfirmed variants were located within repeats, suggesting that variant calling in these regions remains challenging even with pangenomic approaches.

+ *Why does PGGB report fewer SVs than traditional methods?* Graph-based SV calling from PGGB typically reports fewer SVs than assembly-based methods such as PAV or SVIM-asm. This is not a deficiency. PGGB aligns through variable regions, resolving what appears as a single large SV in a linear representation into a series of smaller variants (SNPs, multi-nucleotide polymorphisms (MNPs), small indels) that more accurately describe the actual sequence differences. The multi-method approach (retaining SVs supported by ≥2 callers) balances sensitivity and specificity.

+ *Structural variants as a window into functional diversity.* The pangenome graph fully resolved a complex 82 bp insertion in the _Cd209c_ gene into 7 variable blocks that combined into 6 distinct haplotypes across the RI panel, 4 of which were observed fewer than two times @villani2025 @li2025 @villani2025thesis. This level of resolution is impossible with linear reference-based approaches, which would report a single insertion event. The insertion contained an Lx8b\_3end LINE retrotransposon, and the human ortholog of _Cd209c_ is implicated in multiple infectious diseases. Such complex variants in immune-related genes, enriched for transposable elements, may facilitate rapid adaptive evolution of immune responses. More broadly, structural variants are increasingly recognized as a major and underexplored source of phenotypic variation. Reference-based methods systematically undercount SVs because large insertions, inversions, and complex rearrangements are difficult to detect when the only coordinate system is the genome that lacks them. Pangenome graphs make these variants directly observable: each SV corresponds to an alternative path through the graph, and its frequency across the panel can be read from the number of genomes that traverse it. In the HXB/BXH pangenome, the graph captured variants that were entirely absent from reference-based call sets @villani2025. As the field develops better tools for annotating the functional consequences of SVs (particularly those in regulatory regions, transposable element insertions, and copy number differences) pangenome-derived SV catalogs are likely to explain a portion of the phenotypic variance that remains unaccounted for by SNP-based analyses. The _Cd209c_ example hints at what can be uncovered when graph-based resolution is applied to every variable locus across the genome.

+ *Statistical power and translational potential in recombinant inbred panels.* The appropriate significance threshold for PheWAS in RI populations depends on the number of strains and phenotypes tested. With 30 strains and 60 phenotype classes, we used Bonferroni-corrected Spearman correlations (adjusted p < 0.05) for initial screening, followed by confirmation with a linear mixed model (LMM) correcting for kinship (likelihood ratio statistic, LRS > 16). The LMM should use a leave-one-chromosome-out (LOCO) kinship matrix to prevent proximal contamination---inflated test statistics caused by including the test locus in the kinship estimate. Users should be aware that approximately 30 strains provide limited statistical power, particularly for detecting variants with small effect sizes. Results should be treated as hypothesis-generating and validated in independent cohorts or through functional experiments where possible.

  However, this limitation of statistical power should be weighed against the unique strengths of RI panels. Because each strain is a permanent, isogenic genotype, phenotyping can be repeated indefinitely across time, laboratories, and experimental conditions, allowing effects to be measured with a precision unattainable in outbred populations. The HXB/BXH panel has been phenotyped over more than three decades for hundreds of molecular, physiological, and behavioral traits @mulligan2017, and new phenotypes, including proteomic profiles across brain regions @li2025, continue to be added. Every new phenotype can be immediately tested against the existing pangenome-derived genotypes without additional sequencing, creating a growing resource whose value compounds over time.

  Moreover, the parental strains of the HXB/BXH panel overlap with the founders of heterogeneous stock (HS) rat populations, which have been used for high-resolution mapping of quantitative trait loci in cohorts of thousands of outbred animals. Variants discovered through the pangenome in the RI panel can be imputed into HS cohorts for fine-mapping and validation, bridging the gap between the deep phenotyping of RI strains and the statistical power of outbred populations. Recent cross-species analyses have shown that the cis-genetic architecture of gene expression is similar between rat and human brain tissues, and that genes associated with body composition traits in rats are enriched among human GWAS hits for the same traits. This translational potential makes the HXB/BXH pangenome a resource not only for rat genetics but also for generating hypotheses about human disease mechanisms that can then be tested in clinical datasets. As pangenome-derived variant catalogs become more complete by capturing the structural variants and complex alleles that reference-based methods miss, the translational value of these model organism panels will only increase.

+ *Visualization of pangenome graphs: current state and future needs.* Current pangenome visualization tools, including ODGI @guarracino2022odgi, produce static images. For small subgraphs, tools such as Bandage and GfaViz offer interactive exploration, but no tool yet supports real-time dynamic navigation of chromosome-scale or genome-wide pangenome graphs. This is arguably one of the most significant barriers to broader adoption of pangenomics: researchers who are accustomed to linear genome browsers such as IGV or the UCSC Genome Browser have no equivalent tool for exploring pangenome graphs interactively.

  The challenge is fundamental rather than merely engineering. Pangenome graphs have both linear extent (they span chromosomes and genomes) and branching complexity (each variant site introduces alternative paths). Meaningful visualization must simultaneously convey genomic position, local graph topology, and the distribution of haplotypes across paths, three dimensions of information that a linear layout cannot capture. Recent algorithmic advances have improved the situation: path-guided stochastic gradient descent enables the computation of two-dimensional graph layouts at gigabase scale @heumos2024, and web-based frameworks now project graphs onto linear reference coordinates for interactive inspection. However, a genome browser that lets a researcher zoom seamlessly from a whole-genome overview to a single bubble, inspecting which strains carry which alleles in real time, remains an open goal.

  For practical work today, we recommend a two-tier strategy. First, generate genome-wide overview images, both one-dimensional (showing path coverage and variant density along each chromosome) and two-dimensional (showing the global graph topology). These serve as quality-control diagnostics immediately after graph construction, potentially revealing large-scale problems such as fragmented paths, collapsed repeats, or unexpected structural rearrangements. Second, extract subgraphs for regions of interest (e.g., a QTL peak, a candidate gene, or a complex SV locus) and inspect them with interactive tools. This workflow is practical but far from seamless, and developing better visualization infrastructure should be a priority for the pangenomics community.

+ *Scaling pangenome analysis: from dozens to thousands of genomes.* Explicit pangenome graph construction faces a fundamental scaling constraint: because PGGB's all-to-all alignment strategy compares every input genome to every other, the computational cost grows quadratically with the number of input genomes @garrison2024. For the 32 haplotypes in the HXB/BXH panel, this is manageable, with construction taking hours to days on a modern server. But for hundreds or thousands of haplotypes, the cost becomes prohibitive. Cluster-level parallelization, as implemented in nf-core/pangenome @heumos2024, distributes alignments across computing nodes and has demonstrated construction of pangenome graphs from 1,000 human chromosome 19 haplotypes, but it does not change the underlying quadratic complexity.

  The implicit pangenome graph (IMPG) approach offers a complementary paradigm @guarracino2025impg. Rather than collapsing all alignments into an explicit graph, IMPG treats the pairwise alignment collection itself, together with the transitive relationships it encodes, as a directly queryable pangenome representation. Alignments are indexed using cache-oblivious interval trees (coitrees) and traversed at query time to discover both direct and transitive homology relationships, without materializing a graph. Compact tracepoint-based alignment formats @kaushan2026 and compressed genome archives (AGC) enable the entire representation of hundreds of haplotypes to fit on a single workstation disk.

  Crucially, because each alignment file is indexed independently, incorporating a new genome requires only aligning it to a representative subset, an effort that scales linearly rather than quadratically with cohort size. This solves the "N+1 problem" that plagues explicit graph construction: adding a single new genome to an explicit pangenome graph currently requires rebuilding the entire graph from scratch, whereas IMPG requires only adding incremental alignments and indexing them.

  For the HXB/BXH panel, an implicit graph approach would allow researchers to add newly sequenced RI strains, heterogeneous stock haplotypes, or wild-caught rat genomes without reprocessing the entire pangenome. The partition-lace pipeline offered by IMPG could enable distributed graph construction for larger rat cohorts by splitting the pangenome into manageable partitions, building subgraphs independently, and merging them into unified GFA or VCF outputs. Looking further ahead, IMPG's transitive queries yield pairwise similarity across indexed haplotypes, opening the possibility of computing population genetics summary statistics directly from alignment space, without decomposing variation into biallelic sites. As the rat community sequences additional strains and the cost of long-read sequencing continues to decrease, this incremental, alignment-first framework will be essential for maintaining a growing pangenomic resource that expands as new data become available, rather than a static artifact that must be periodically rebuilt from scratch.

+ *From Linked-Reads to complete assemblies: the trajectory of assembly quality.* The HXB/BXH pangenome described in this protocol was built from 10x Genomics Linked-Read assemblies, which, while sufficient to demonstrate the value of the pangenome approach, have inherent limitations: lower contiguity than long-read assemblies, more unresolved gaps, and difficulty resolving repetitive regions and complex structural variants. These limitations inflate estimates of non-reference content (as discussed in *Note 1*), obscure the true structure of complex loci, and reduce confidence in SV calls.

  Long-read sequencing technologies have matured rapidly. PacBio HiFi reads now routinely yield contig N50 values exceeding 20 Mb, and Oxford Nanopore ultra-long reads enable scaffolding across centromeric and pericentromeric repeats. In the mouse, these advances have already produced 17 high-quality long-read assemblies spanning classical laboratory and wild-derived strains @helmy2026, with two strains (C57BL/6J and CAST/EiJ) reaching telomere-to-telomere completeness, adding 213 Mb of new sequence and 517 protein-coding genes to the reference @francis2025. For the rat, the mRatBN7.2 reference assembly has been substantially improved @dejong2024, and near-complete assemblies are emerging, but multi-strain long-read assemblies on the scale of the mouse project are not yet available.

  Reassembling the HXB/BXH strains with long-read technology would transform the pangenome in several ways. First, it would eliminate the gap-related inflation of non-reference content, yielding a cleaner separation between genuine novel sequence and assembly artifacts. Second, it would improve resolution of structural variants, particularly in regions rich in repetitive elements, segmental duplications, and transposable element insertions, precisely the regions where pangenome graphs add the most value over linear references. Third, it would enable more complete annotation of strain-specific genes and regulatory elements, connecting structural variation to functional consequences. The decreasing cost of long-read sequencing makes this investment increasingly feasible, and the analytical pipeline described in this protocol would apply without modification to assemblies from any technology.

+ *The future of pangenomics in model organisms.* Model organisms occupy a unique position in the pangenomics landscape. Unlike human populations, where sample collection, consent, and phenotyping are constrained by practical and ethical considerations, model organism panels offer controlled genetic backgrounds, unlimited biological replicates, and the ability to phenotype the same genotype under different experimental conditions indefinitely. Inbred strains are effectively haploid, eliminating the need for computational phasing. And the deep phenotyping that panels like HXB/BXH have accumulated over decades, with hundreds of traits spanning cardiovascular physiology, metabolism, neurobehavior, gene expression, and now proteomics @mulligan2017 @li2025. This provides a phenotypic resolution that no human cohort can match.

  These advantages make model organisms ideal proving grounds for pangenomic methods. New algorithms for graph construction, variant calling, and genotype-phenotype association can be developed and validated in a setting where the ground truth is more accessible and the biology more controlled. Lessons learned from building and querying a rat pangenome (parameter tuning, quality metrics, statistical approaches for association mapping from graph-derived genotypes) transfer to other species, including humans. In this sense, the HXB/BXH pangenome serves not only as a resource for rat genetics but as a methodological testbed for the broader field.

  Looking forward, several developments are poised to expand the utility of pangenomics in model organisms. The integration of pangenome-derived variants with multi-omic data will enable researchers to trace the functional consequences of structural variation from DNA through RNA and protein to phenotype. Recent work mapping protein quantitative trait loci across the HXB/BXH panel demonstrated that pangenome-informed variant calling improved the identification of candidate genes underlying pQTLs @li2025, a preview of what becomes possible when graph-derived genotypes are combined with molecular phenotypes.

  Personalized pangenome references, in which the full graph is subsampled to match an individual's haplotype composition, have shown a fourfold reduction in genotyping errors for human data @siren2021. Adapting this concept to model organisms, where the set of possible haplotypes is known, could further improve variant calling accuracy for RI and outbred panels alike. For heterogeneous stock rats, where thousands of animals are genotyped at low coverage and imputed against a reference panel, a pangenome-aware imputation framework would capture structural variants that are currently invisible to SNP-array-based approaches.

  Perhaps most importantly, the pangenome provides a natural framework for integrating data across related populations. The HXB/BXH RI strains, the HS outbred rats, congenic lines, and newly sequenced wild-caught _R. norvegicus_ all share overlapping genetic variation. A unified pangenome graph that encompasses these populations would enable cross-population analyses, transferring QTL discoveries from the RI panel to fine-mapping in the HS, validating findings in congenic lines, and contextualizing laboratory variation against wild diversity. Building such an integrated resource will require the scaling approaches discussed in *Note 14*, but the payoff would be a comprehensive genotype--phenotype map for one of the most deeply studied organisms in biomedical research.

  The tools and workflows described in this protocol are a starting point. As assembly quality improves (_see_ *Note 15*), as graph construction scales to larger cohorts, and as the analytical ecosystem matures, pangenomics has the potential to reshape how genetic variation is studied in model organisms, moving from the single-reference, SNP-centric paradigm that has dominated the field for two decades toward a graph-based framework that captures the full complexity of genome evolution and its consequences for phenotypic diversity. The rat, with its compact genetic diversity, deep phenotyping infrastructure, and growing genomic resources, is well positioned to lead this transition.
