= Discussion

In time we expect the pangenome-based methods to replace the single linear reference metods particularly for variant detection and transcriptome. With this chapter on the rat we aim to show that the tools for building a pangenome exist and can be applied generally. We foresee an intermediate phase where existing pipelines and workflows start adding pangenome tooling, i.e., a hybrid solution that allows for enhanced variant detection and transcriptome mapping.

PGGB's all-to-all alignment strategy scales quadratically with the number of input haplotypes, so building graphs from hundreds or thousands of genomes becomes prohibitive and adding a single new genome forces a full rebuild @garrison2024. Cluster-level parallelization such as nf-core/pangenome distributes alignments across nodes @heumos2024 but does not change the asymptotic cost. The implicit pangenome graph (IMPG) approach indexes pairwise alignments with cache-oblivious interval trees and resolves transitive homology at query time @guarracino2025impg, so adding a genome requires only aligning it to a representative subset. Together with compact tracepoint-based alignment formats @kaushan2026 and AGC-compressed archives @deorowicz2023, this makes it feasible to grow the rat pangenome incrementally, adding further HRDP strains, heterogeneous stock (HS) haplotypes, and wild-caught _R. norvegicus_ without rebuilding from scratch.

The HXB/BXH pangenome described here is built from 10x Linked-Read assemblies, which inflate estimates of non-reference content (_see_ *Note 1*) and limit resolution of repetitive and complex loci. PacBio HiFi and Oxford Nanopore ultra-long reads now routinely deliver contig N50 values above 20 Mb; recent work in the mouse produced 17 long-read strain assemblies including two telomere-to-telomere lines @helmy2026 @francis2025, and in the rat the reference has advanced to GRCr8 @li2024grcr8 with additional long-read strain assemblies available @kalbfleisch2024. Reassembling the HXB/BXH strains with long reads would remove gap-related inflation of non-reference content, improve SV resolution in repeat- and TE-rich regions, and refine strain-specific annotation. The workflow in this protocol applies without modification to assemblies from any technology.

Interactive visualization at chromosome scale remains a bottleneck for broader uptake of pangenomics. ODGI produces static 1D and 2D layouts useful for quality control @guarracino2022odgi; for small subgraphs, Bandage @wick2015, GfaViz @gonnella2019, and Sequence Tube Map @beyer2019 support point-and-click navigation. Recent tools such as PangyPlot @mastromatteo2025 combine ODGI's 2D layout with a D3 force-directed engine @bostock2011 and hierarchical bubble abstraction to offer coordinate-based, IGV-like navigation of chromosome-scale graphs, and path-guided stochastic gradient descent supports layouts at gigabase scale @heumos2024pgsgd. Until these tools mature, a two-tier workflow is practical: whole-genome 1D/2D overviews for quality control followed by subgraph extraction for interactive inspection of regions of interest.

Model-organism panels are natural proving grounds for pangenomic methods, offering controlled genetic backgrounds, unlimited replicates, and haploid inbred assemblies that remove the need for computational phasing, alongside decades of accumulated phenotype data @mulligan2017 @li2025. Personalized pangenome references, which subsample the graph to match an individual's haplotype composition, have shown a fourfold reduction in genotyping errors for human data @siren2024 and translate directly to RI and heterogeneous-stock panels where the haplotype set is known. Integrating the HXB/BXH RI strains, HS outbred cohorts, congenic lines, and wild-caught _R. norvegicus_ into a single pangenome would enable QTL transfer, fine-mapping, and cross-population validation within one framework, complementing the pQTL and multi-omic work already underway on this panel @li2025 @villani2025.

= Notes

+ *Linked-Read technology considerations.* 10x Genomics Chromium Linked-Reads are #text(red)[not ideal] for de novo assembly compared to long-read technologies (PacBio HiFi, Oxford Nanopore). Note that 10x Genomics has discontinued the Chromium Linked-Read product; however, the HXB/BXH assemblies used in this protocol were generated before discontinuation, and the analytical workflow applies equally to assemblies from any sequencing technology. Linked-Read assemblies tend to have more unresolved regions (stretches of Ns) than long-read assemblies, which leads to an overestimation of non-reference sequence when Ns are included in the counting. In the HXB/BXH pangenome, the non-reference content rose from 0.18 Gb (excluding Ns) to 3.9 Gb (including Ns). Even so, the pangenome still captured substantial genuine novel variation. As long-read sequencing costs continue to decrease, reassembling these strains with PacBio HiFi or Oxford Nanopore would yield more contiguous assemblies and more complete pangenomes.

+ *Handling heterozygous strains.* Among the 31 HXB/BXH strains, BXH2 showed 7.7% heterozygous variants, likely due to a recent breeding error @dejong2024. In principle, such a strain can still be included in the pangenome as a haploid assembly if the assembler selected one haplotype consistently. However, results for this strain should be interpreted with caution, as the assembly may switch between haplotypes in some regions.

+ *Linear reference genome inclusion rationale.* Although PGGB is reference-free, including the standard linear reference genome (mRatBN7.2) in the graph is essential for practical reasons. It provides a coordinate system for variant calling (via the `-V` flag), it enables comparison with existing reference-based datasets, and it allows annotation with established gene models. The reference is treated as just another genome in the graph and does not receive any special treatment during construction.

+ *Choosing between PGGB and Minigraph-Cactus.* Both tools can produce high-quality pangenome graphs, but they differ in how well their output integrates with downstream tools, particularly vg Giraffe @siren2021. MC graphs have a linear high-level structure that Giraffe's distance indexing is designed for, making them the recommended input for short-read mapping. PGGB graphs can also be used with Giraffe after node chopping (Section 3.5), but their more complex topology (large snarls, deeply nested variants, non-linear high-level structure) can cause the distance index to require prohibitive memory or fail entirely for large or highly divergent genomes. For smaller, lower-diversity panels such as HXB/BXH, per-chromosome PGGB graphs are tractable with Giraffe; for larger cohorts or more complex genomes, users should expect to use MC graphs for read mapping even if they prefer PGGB for graph construction and variant calling. The choice of graph builder also depends on the biological question. PGGB is preferred when you need a strictly reference-free graph (e.g., no single genome is a natural reference, or you want to avoid any reference bias), when the input set is moderate in size (tens to low hundreds of haplotypes), or when full base-level resolution of all variation, including within repetitive regions, is important. Minigraph-Cactus is the better choice when a reliable linear reference genome exists and a reference-anchored graph is acceptable, when the input set is very large (hundreds to thousands of haplotypes) and computational efficiency is a priority, or when the dataset is simply too large for all-to-all alignment. For the HXB/BXH panel (32 haplotypes, closely related inbred strains), PGGB was the natural choice because reference-free construction avoids privileging either parental genome.

+ *Percent identity parameter selection.* The `-p` parameter sets the minimum percent identity for WFMASH mappings. For closely related inbred strains derived from the same species (such as HXB/BXH rats or BXD mice), values of 95-98% are appropriate. For interspecies comparisons or highly divergent populations, lower values (85-90%) may be needed. Setting this value too low will increase runtime and may introduce spurious alignments; setting it too high will miss genuinely divergent regions.

+ *Segment length parameter.* The `-s` parameter controls the minimum length of mapping segments. Shorter values increase sensitivity but also increase runtime and may capture more spurious short alignments. For closely related mammalian genomes, values between 1,000 and 10,000 bp typically work well.

+ *Sparsification and k-mer filtering for large genome numbers.* All-to-all alignment scales quadratically with the number of input genomes. Two PGGB parameters help manage this. The `-F` parameter sets a k-mer frequency filter threshold: setting `-F 0.001` ignores the top 0.1% most frequent k-mers in minmer sketches, reducing spurious alignments in repetitive regions. For scaling the number of pairwise comparisons themselves, the `-x` parameter activates Erdős-Rényi random sparsification, which randomly subsamples the set of pairwise comparisons. Because SEQWISH recovers transitive homology relationships (if A aligns to B and B to C, then A-C is inferred), the loss of direct alignments is mitigated. With sparsification, a 10× increase in input genomes requires approximately 20× runtime increase rather than 100×. For 32 genomes, the benefit is moderate; for hundreds of genomes, it becomes essential.

+ *Chromosome-by-chromosome construction and troubleshooting.* For mammalian-scale genomes, constructing the pangenome one chromosome at a time is practical and recommended. This reduces peak memory requirements, enables parallel execution across cluster nodes, and simplifies debugging. The resulting per-chromosome GFA and VCF files can be concatenated for genome-wide analyses. PGGB can resume interrupted runs: add the `-r` (`--resume`) flag when restarting with the same output directory, and PGGB will skip stages whose outputs already exist. Common failures include out-of-memory during SMOOTHXG (reduce `-G` block sizes), excessively slow WFMASH alignment (use `-x` sparsification), and fragmented graphs with poor path coverage (verify that `-p` is not set too high for the dataset's divergence).

+ *Variant calling precision in repetitive regions.* Genome-wide accuracy of pangenome-derived variants compared to joint calling was approximately 90%. Exceptions included chromosomes Y and 16, where assembly complexity (chromosome Y) and an abundance of complex variants (chromosome 16) reduced concordance. Within repetitive regions, Sanger validation showed that approximately 90% of unconfirmed variants were located within repeats, suggesting that variant calling in these regions remains challenging even with pangenomic approaches.

+ *Why does PGGB report fewer SVs than traditional methods?* Graph-based SV calling from PGGB typically reports fewer SVs than assembly-based methods such as PAV or SVIM-asm. This is not a deficiency. PGGB aligns through variable regions, resolving what appears as a single large SV in a linear representation into a series of smaller variants (SNPs, multi-nucleotide polymorphisms (MNPs), small indels) that more accurately describe the actual sequence differences. The multi-method approach (retaining SVs supported by ≥2 callers) balances sensitivity and specificity.

+ *Structural variants as a window into functional diversity.* The pangenome graph fully resolved a complex 82 bp insertion in the _Cd209c_ gene into 7 variable blocks that combined into 6 distinct haplotypes across the RI panel, 4 of which were observed fewer than two times @villani2025 @villani2025thesis. This level of resolution is impossible with linear reference-based approaches, which would report a single insertion event. The insertion contained an Lx8b\_3end LINE retrotransposon, and the human ortholog of _Cd209c_ is implicated in multiple infectious diseases. Such complex variants in immune-related genes, enriched for transposable elements, may facilitate rapid adaptive evolution of immune responses. Structural variants represent a major and underexplored source of phenotypic variation, and we have been systematically undercounting them for years. Reference-based methods miss large insertions, inversions, and complex rearrangements because the only coordinate system available is the genome that lacks them. #text(red)[Pangenome graphs change this picture entirely], because each SV corresponds to an alternative path through the graph, and its frequency across the panel can be read directly from the number of genomes that traverse it. In the HXB/BXH pangenome, the graph captured variants that were entirely absent from reference-based call sets @villani2025. As the field develops better tools for annotating the functional consequences of SVs (particularly those in regulatory regions, transposable element insertions, and copy number differences) pangenome-derived SV catalogs are likely to explain a portion of the phenotypic variance.

+ *Statistical power and translational potential in recombinant inbred panels.* The appropriate significance threshold for PheWAS in RI populations depends on the number of strains and phenotypes tested. For panels of similar size (around 30 strains and 60 phenotype classes), use Bonferroni-corrected Spearman correlations (adjusted p < 0.05) for initial screening, then confirm with a linear mixed model (LMM) correcting for kinship (likelihood ratio statistic, LRS > 16). The LMM should use a leave-one-chromosome-out (LOCO) kinship matrix to prevent proximal contamination (inflated test statistics caused by including the test locus in the kinship estimate). Users should be aware that approximately 30 strains provide limited statistical power, particularly for detecting variants with small effect sizes. Results should be treated as hypothesis-generating and validated in independent cohorts or through functional experiments where possible.

  That said, this limitation should be weighed against the unique strengths of RI panels. Because each strain is a permanent, isogenic genotype, phenotyping can be repeated indefinitely across time, laboratories, and experimental conditions, allowing effects to be measured with a precision unattainable in outbred populations. The HXB/BXH panel has been phenotyped over more than three decades for hundreds of molecular, physiological, and behavioral traits @mulligan2017, and new phenotypes (including proteomic profiles across brain regions @li2025) continue to be added. Every new phenotype can be immediately tested against the existing pangenome-derived genotypes without additional sequencing, creating a growing resource whose value compounds over time.

  It also helps that the parental strains of the HXB/BXH panel overlap with the founders of heterogeneous stock (HS) rat populations, which have been used for high-resolution mapping of quantitative trait loci in cohorts of thousands of outbred animals. Variants discovered through the pangenome in the RI panel can be imputed into HS cohorts for fine-mapping and validation, bridging the gap between the deep phenotyping of RI strains and the statistical power of outbred populations. #text(red)[Recent cross-species analyses have been encouraging on this front,] showing that the cis-genetic architecture of gene expression is similar between rat and human brain tissues, and that genes associated with body composition traits in rats are enriched among human GWAS hits for the same traits. This translational potential makes the HXB/BXH pangenome a resource not only for rat genetics but also for generating hypotheses about human disease mechanisms that can then be tested in clinical datasets. As pangenome-derived variant catalogs become more complete by capturing the structural variants and complex alleles that reference-based methods miss, #text(red)[the translational value of these model organism panels will only increase.]

